import { createStoredZip } from '@programkit/core'

import {
  codexManifestSource,
  portableManifestSource,
  sharedPluginSources,
} from './agent-plugin-source.generated.ts'
const bearerTokenEnvironmentVariable = 'PROGRAMKIT_API_KEY'
const reproducibleZipTimestamp = new Date('1980-01-01T00:00:00.000Z')

function json(value: unknown) {
  return `${JSON.stringify(value, null, 2)}\n`
}

function pluginInstallGuide(endpoint: string) {
  return `# Connect ProgramKit to an agent

This bundle was generated by your ProgramKit deployment for:

${endpoint}

The plugin is installed in your agent client. It is not another server to deploy.

1. In ProgramKit, open Infrastructure & API and create an Agent operations key.
2. Save the copy-once secret as ${bearerTokenEnvironmentVariable} in the agent client's environment.
3. Install the ./programkit directory in an Agent Plugins-compatible client.

For Codex, run these commands from the unzipped bundle directory:

    codex plugin marketplace add .
    codex plugin add programkit@programkit

Start a new agent session after installation. The portable mcp.json intentionally contains no
credential: Agent Plugins 1.0 leaves authentication and secret storage to the client.
`
}

export function createAgentPluginBundle(origin: string, modifiedAt = reproducibleZipTimestamp) {
  const endpoint = new URL('/mcp', origin).toString()
  const files: Array<{ name: string; text: string }> = [
    { name: 'INSTALL.md', text: pluginInstallGuide(endpoint) },
    { name: 'programkit/plugin.json', text: portableManifestSource },
    { name: 'programkit/.codex-plugin/plugin.json', text: codexManifestSource },
    {
      name: 'programkit/mcp.json',
      text: json({
        $schema: 'https://agent-plugins.org/schemas/1.0.0/mcp.schema.json',
        mcpServers: { programkit: { type: 'streamable-http', url: endpoint } },
      }),
    },
    {
      name: 'programkit/.mcp.json',
      text: json({
        mcpServers: {
          programkit: {
            type: 'http',
            url: endpoint,
            bearer_token_env_var: bearerTokenEnvironmentVariable,
          },
        },
      }),
    },
    {
      name: '.agents/plugins/marketplace.json',
      text: json({
        name: 'programkit',
        interface: { displayName: 'ProgramKit' },
        plugins: [
          {
            name: 'programkit',
            source: { source: 'local', path: './programkit' },
            policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
            category: 'Productivity',
          },
        ],
      }),
    },
  ]

  for (const [sourcePath, text] of Object.entries(sharedPluginSources)) {
    files.push({ name: `programkit/${sourcePath}`, text })
  }

  return {
    endpoint,
    filename: 'programkit-agent-plugin.zip',
    archive: createStoredZip(files, modifiedAt),
  }
}
