import type { OperationDefinition } from './types.ts'

export const operationManifest = [
  {
    name: 'event.update',
    title: 'Update event settings',
    description: 'Update the active event identity, venue, dates, timezone, or lifecycle status.',
    kind: 'command',
    scopes: ['events:write'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['eventId'],
    emits: ['event.updated'],
  },
  {
    name: 'submission-form.create',
    title: 'Create submission form',
    description: 'Create an event-scoped CFP or guaranteed-session form and its ordered fields.',
    kind: 'command',
    scopes: ['submission-forms:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'slug', 'title'],
    emits: ['submission-form.created'],
  },
  {
    name: 'submission-form.update',
    title: 'Update submission form',
    description:
      'Update form settings or atomically replace its ordered fields and conditional rules.',
    kind: 'command',
    scopes: ['submission-forms:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId'],
    emits: ['submission-form.updated'],
  },
  {
    name: 'submission-form.publish',
    title: 'Publish submission form',
    description: 'Validate and open a submission form at its public slug.',
    kind: 'command',
    scopes: ['submission-forms:publish'],
    risk: 'public',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId'],
    emits: ['submission-form.published'],
  },
  {
    name: 'submission.create',
    title: 'Create submission draft',
    description: 'Create a private draft response to an open event submission form.',
    kind: 'command',
    scopes: ['submissions:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId', 'kind', 'answers'],
    emits: ['submission.created'],
  },
  {
    name: 'submission.submit',
    title: 'Submit proposal',
    description:
      'Validate a draft, submit it, assign its first evaluation round, and prepare a durable confirmation receipt.',
    kind: 'command',
    scopes: ['submissions:submit'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['submissionId'],
    emits: ['submission.submitted', 'submission.receipt-queued'],
  },
  {
    name: 'submission.record-receipt-delivery',
    title: 'Record submission receipt delivery result',
    description:
      'Record a trusted email-provider result for a frozen submission confirmation receipt.',
    kind: 'command',
    scopes: ['communications:deliver'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['deliveryId', 'status'],
    emits: ['submission.receipt-delivered', 'submission.receipt-delivery-failed'],
  },
  {
    name: 'review.submit-scorecard',
    title: 'Submit review scorecard',
    description: 'Score an assigned submission against its evaluation plan rubric.',
    kind: 'command',
    scopes: ['reviews:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['assignmentId', 'scores', 'recommendation'],
    emits: ['review.scorecard-submitted'],
  },
  {
    name: 'review.decide',
    title: 'Decide submission',
    description:
      'Accept, reject, or waitlist a reviewed submission; acceptance creates the speaker and session records.',
    kind: 'command',
    scopes: ['reviews:decide'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['submissionId', 'decision'],
    emits: [
      'review.decision-recorded',
      'person.created',
      'participation.created',
      'session.created-from-submission',
    ],
  },
  {
    name: 'person.create',
    title: 'Create person',
    description: 'Create a person and an event participation record.',
    kind: 'command',
    scopes: ['people:write', 'participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['firstName', 'lastName', 'email'],
    emits: ['person.created', 'participation.created'],
  },
  {
    name: 'person.update',
    title: 'Update person',
    description: 'Update contact or public profile fields for a person.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['personId'],
    emits: ['person.updated'],
  },
  {
    name: 'participation.set-status',
    title: 'Set participation status',
    description: 'Move a participant through the invitation and confirmation lifecycle.',
    kind: 'command',
    scopes: ['participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['participationId', 'status'],
    emits: ['participation.status-changed'],
  },
  {
    name: 'requirement.set-status',
    title: 'Review requirement',
    description: 'Submit, approve, waive, or request revision on a readiness requirement.',
    kind: 'command',
    scopes: ['requirements:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['requirementInstanceId', 'status'],
    emits: ['requirement.status-changed', 'participation.readiness-changed'],
  },
  {
    name: 'requirement.submit-file',
    title: 'Submit requirement file',
    description:
      'Attach a privately stored file to an owned speaker requirement and submit it for review.',
    kind: 'command',
    scopes: ['requirements:write', 'assets:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['requirementInstanceId', 'filename', 'contentType', 'sizeBytes', 'storageKey'],
    emits: ['asset.created', 'requirement.status-changed', 'participation.readiness-changed'],
  },
  {
    name: 'portal.update-profile',
    title: 'Update participant profile',
    description: 'Allow a participant to update their own public profile fields.',
    kind: 'command',
    scopes: ['portal:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['participationId'],
    emits: ['participant.profile-updated'],
  },
  {
    name: 'schedule.place-session',
    title: 'Place session',
    description: 'Add an unscheduled session to the draft agenda and recalculate conflicts.',
    kind: 'command',
    scopes: ['schedule:draft'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['sessionId', 'roomId', 'startsAt'],
    emits: ['schedule.session-placed'],
  },
  {
    name: 'schedule.move-session',
    title: 'Move session',
    description: 'Move a session to another room or start time and recalculate conflicts.',
    kind: 'command',
    scopes: ['schedule:draft'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['placementId', 'roomId', 'startsAt'],
    emits: ['schedule.session-moved'],
  },
  {
    name: 'schedule.unplace-session',
    title: 'Return session to unscheduled',
    description: 'Remove one placement from the draft while leaving its session available.',
    kind: 'command',
    scopes: ['schedule:draft'],
    risk: 'public',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['placementId'],
    emits: ['schedule.session-unplaced'],
  },
  {
    name: 'schedule.publish',
    title: 'Publish schedule',
    description:
      'Publish the complete, changed, conflict-free draft schedule as a new immutable version.',
    kind: 'command',
    scopes: ['schedule:publish'],
    risk: 'public',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: [],
    emits: ['schedule.published'],
  },
  {
    name: 'accelevents.prepare-export',
    title: 'Prepare Accelevents export',
    description:
      'Freeze the latest published speakers and sessions into a versioned Accelevents delivery outbox.',
    kind: 'command',
    scopes: ['integrations:export'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['eventUrl'],
    emits: ['accelevents.export-prepared'],
  },
  {
    name: 'accelevents.record-result',
    title: 'Record Accelevents export result',
    description:
      'Record a trusted provider result for one frozen Accelevents speaker or session item.',
    kind: 'command',
    scopes: ['integrations:deliver'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['exportId', 'itemId', 'status'],
    emits: ['accelevents.item-delivered', 'accelevents.item-failed'],
  },
  {
    name: 'campaign.create-draft',
    title: 'Draft campaign',
    description: 'Create a targeted message draft with a calculated audience.',
    kind: 'command',
    scopes: ['communications:draft'],
    risk: 'internal',
    agentPolicy: 'execute',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'subject', 'body', 'audience'],
    emits: ['campaign.drafted'],
  },
  {
    name: 'campaign.submit',
    title: 'Submit campaign',
    description: 'Submit a campaign for human approval.',
    kind: 'command',
    scopes: ['communications:draft'],
    risk: 'internal',
    agentPolicy: 'execute',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['campaignId'],
    emits: ['campaign.submitted'],
  },
  {
    name: 'campaign.approve',
    title: 'Approve campaign',
    description: 'Approve an exact campaign version and recipient set.',
    kind: 'command',
    scopes: ['communications:approve'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['campaignId'],
    emits: ['campaign.approved'],
  },
  {
    name: 'campaign.send',
    title: 'Queue campaign delivery',
    description:
      'Create a durable per-recipient outbox for an approved campaign without claiming provider delivery.',
    kind: 'command',
    scopes: ['communications:send'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['campaignId'],
    emits: ['campaign.queued'],
  },
  {
    name: 'campaign.record-delivery',
    title: 'Record campaign delivery result',
    description:
      'Record a trusted email-provider delivery result and close the campaign when every recipient is terminal.',
    kind: 'command',
    scopes: ['communications:deliver'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['deliveryId', 'status'],
    emits: ['campaign.delivery-succeeded', 'campaign.delivery-failed'],
  },
  {
    name: 'change-set.create',
    title: 'Create change set',
    description: 'Create a reviewable proposal containing one or more operations.',
    kind: 'command',
    scopes: ['changes:propose'],
    risk: 'internal',
    agentPolicy: 'execute',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['title', 'operations'],
    emits: ['change-set.created'],
  },
  {
    name: 'change-set.approve',
    title: 'Approve change set',
    description: 'Approve a validated proposal for commit.',
    kind: 'command',
    scopes: ['changes:approve'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['changeSetId'],
    emits: ['change-set.approved'],
  },
  {
    name: 'change-set.reject',
    title: 'Reject change set',
    description: 'Reject a proposed change set without applying its operations.',
    kind: 'command',
    scopes: ['changes:approve'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['changeSetId'],
    emits: ['change-set.rejected'],
  },
  {
    name: 'change-set.commit',
    title: 'Commit change set',
    description: 'Revalidate and atomically apply an approved proposal.',
    kind: 'command',
    scopes: ['changes:commit'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['changeSetId'],
    emits: ['change-set.committed'],
  },
  {
    name: 'workspace.reset-demo',
    title: 'Reset demo workspace',
    description: 'Replace the workspace with the deterministic demonstration dataset.',
    kind: 'command',
    scopes: ['workspace:admin'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: [],
    emits: ['workspace.reset'],
  },
] as const satisfies readonly OperationDefinition[]

export type OperationName = (typeof operationManifest)[number]['name']

export function operationDefinition(name: string) {
  return operationManifest.find((operation) => operation.name === name)
}
