import type { OperationDefinition } from './types.ts'

export const operationManifest = [
  {
    name: 'event.update',
    title: 'Update event settings',
    description: 'Update the active event identity, venue, dates, timezone, or lifecycle status.',
    kind: 'command',
    scopes: ['events:write'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['eventId'],
    emits: ['event.updated'],
  },
  {
    name: 'track.create',
    title: 'Create program track',
    description: 'Add a named, color-coded track to the active event.',
    kind: 'command',
    scopes: ['events:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name'],
    emits: ['track.created'],
  },
  {
    name: 'room.create',
    title: 'Create event room',
    description: 'Add a schedulable room and capacity to the active event.',
    kind: 'command',
    scopes: ['events:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'capacity'],
    emits: ['room.created'],
  },
  {
    name: 'session.create',
    title: 'Create program session',
    description: 'Create a draft or approved session and connect its speakers to it.',
    kind: 'command',
    scopes: ['sessions:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: [
      'title',
      'summary',
      'format',
      'trackId',
      'durationMinutes',
      'expectedAttendance',
    ],
    emits: ['session.created'],
  },
  {
    name: 'session.update',
    title: 'Update program session',
    description: 'Update session content, format, track, speakers, or approval status.',
    kind: 'command',
    scopes: ['sessions:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['sessionId'],
    emits: ['session.updated'],
  },
  {
    name: 'session.restore',
    title: 'Restore session version',
    description: 'Restore session content and settings from a recorded change.',
    kind: 'command',
    scopes: ['sessions:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['sessionId', 'eventId'],
    emits: ['session.restored'],
  },
  {
    name: 'submission-form.create',
    title: 'Create submission form',
    description: 'Create an event-scoped CFP or guaranteed-session form and its ordered fields.',
    kind: 'command',
    scopes: ['submission-forms:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'slug', 'title'],
    emits: ['submission-form.created'],
  },
  {
    name: 'submission-form.update',
    title: 'Update submission form',
    description:
      'Update form settings or atomically replace its ordered fields and conditional rules.',
    kind: 'command',
    scopes: ['submission-forms:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId'],
    emits: ['submission-form.updated'],
  },
  {
    name: 'submission-form.publish',
    title: 'Publish submission form',
    description: 'Validate and open a submission form at its public slug.',
    kind: 'command',
    scopes: ['submission-forms:publish'],
    risk: 'public',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId'],
    emits: ['submission-form.published'],
  },
  {
    name: 'submission.create',
    title: 'Create submission draft',
    description: 'Create a private draft response to an open event submission form.',
    kind: 'command',
    scopes: ['submissions:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId', 'kind', 'answers'],
    emits: ['submission.created'],
  },
  {
    name: 'submission.submit',
    title: 'Submit proposal',
    description: 'Validate a draft, submit it, and assign its first evaluation round.',
    kind: 'command',
    scopes: ['submissions:submit'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['submissionId'],
    emits: ['submission.submitted'],
  },
  {
    name: 'submission.update',
    title: 'Update submission',
    description: 'Update a speaker-owned proposal, its files, or its co-presenters.',
    kind: 'command',
    scopes: ['submissions:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['submissionId'],
    emits: ['submission.updated'],
  },
  {
    name: 'reviewer.create',
    title: 'Add reviewer',
    description: 'Add a reviewer to the active event.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'email'],
    emits: ['reviewer.created'],
  },
  {
    name: 'reviewer-team.create',
    title: 'Create reviewer pool',
    description: 'Create an event-scoped reviewer pool for an evaluation round.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'reviewerIds'],
    emits: ['reviewer-team.created'],
  },
  {
    name: 'reviewer-team.update',
    title: 'Update reviewer pool',
    description: 'Rename a reviewer pool or replace its event-scoped membership.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['teamId'],
    emits: ['reviewer-team.updated'],
  },
  {
    name: 'evaluation-plan.create',
    title: 'Create evaluation plan',
    description:
      'Create an event review plan with independent rounds, category routing, pools, and scorecards.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['formId', 'name', 'rounds'],
    emits: ['evaluation-plan.created'],
  },
  {
    name: 'evaluation-plan.update',
    title: 'Update evaluation plan',
    description:
      'Update review rounds, dates, category routes, reviewer pools, identity rules, and scorecards.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['planId'],
    emits: ['evaluation-plan.updated'],
  },
  {
    name: 'review.assign',
    title: 'Assign reviews',
    description:
      'Assign one or more eligible submissions to a reviewer, with optional track filters and a reviewer cap.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['evaluationPlanId', 'roundId', 'reviewerId', 'submissionIds'],
    emits: ['reviewer-assignment.created'],
  },
  {
    name: 'review.unassign',
    title: 'Remove review assignment',
    description: 'Remove an incomplete reviewer assignment from the active event.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['assignmentId'],
    emits: ['reviewer-assignment.removed'],
  },
  {
    name: 'review.remind',
    title: 'Remind reviewers',
    description: 'Send a reminder to reviewers who still have outstanding assignments.',
    kind: 'command',
    scopes: ['reviews:configure'],
    risk: 'external',
    agentPolicy: 'propose_only',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['reviewerIds'],
    emits: ['reviewer.reminder-sent'],
  },
  {
    name: 'review.recuse',
    title: 'Declare review conflict',
    description: 'Recuse the assigned reviewer from one proposal while preserving an audit trail.',
    kind: 'command',
    scopes: ['reviews:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['assignmentId'],
    emits: ['reviewer-assignment.recused'],
  },
  {
    name: 'review.restore-recusal',
    title: 'Undo review conflict',
    description: 'Restore a recused proposal to the assigned reviewer’s actionable queue.',
    kind: 'command',
    scopes: ['reviews:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['assignmentId'],
    emits: ['reviewer-assignment.recusal-restored'],
  },
  {
    name: 'review.submit-scorecard',
    title: 'Submit review scorecard',
    description: 'Score an assigned submission against its evaluation plan rubric.',
    kind: 'command',
    scopes: ['reviews:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['assignmentId'],
    emits: ['review.scorecard-submitted'],
  },
  {
    name: 'review.decide',
    title: 'Decide submission',
    description:
      'Accept, reject, or waitlist a reviewed submission; acceptance creates the speaker and session records.',
    kind: 'command',
    scopes: ['reviews:decide'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['submissionId', 'decision'],
    emits: [
      'review.decision-recorded',
      'person.created',
      'participation.created',
      'session.created-from-submission',
      'session.cancelled-from-submission',
    ],
  },
  {
    name: 'submission.notify-decision',
    title: 'Queue decision email',
    description: 'Render and queue the recorded submission decision for its submitter.',
    kind: 'command',
    scopes: ['reviews:decide'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['submissionId'],
    emits: ['submission.decision-notice-queued'],
  },
  {
    name: 'person.create',
    title: 'Create person',
    description: 'Create a person and an event participation record.',
    kind: 'command',
    scopes: ['people:write', 'participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['firstName', 'lastName', 'email'],
    emits: ['person.created', 'participation.created'],
  },
  {
    name: 'person.add-note',
    title: 'Add contact note',
    description: 'Add an internal, timestamped note to an organization contact.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['personId', 'body'],
    emits: ['person.note-added'],
  },
  {
    name: 'person.add-to-event',
    title: 'Add contact to event',
    description: 'Reuse an organization contact in an event without re-entering profile data.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['personId', 'eventId'],
    emits: ['participation.created'],
  },
  {
    name: 'person.reuse-in-event',
    title: 'Reuse contact in active event',
    description:
      'Reuse a known organization contact in the active event while preserving their stable identity.',
    kind: 'command',
    scopes: ['people:write', 'participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['personId', 'firstName', 'lastName', 'email'],
    emits: ['person.created', 'participation.created'],
  },
  {
    name: 'person.merge',
    title: 'Merge duplicate contacts',
    description: 'Merge a duplicate person into a chosen primary contact and preserve links.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'administrative',
    agentPolicy: 'propose_only',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['primaryPersonId', 'duplicatePersonId'],
    emits: ['person.merged'],
  },
  {
    name: 'crm.segment.create',
    title: 'Save CRM segment',
    description: 'Save a dynamic filter or curated contact set as a reusable segment.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'mode'],
    emits: ['crm.segment-created'],
  },
  {
    name: 'crm.pipeline.enroll',
    title: 'Enroll speaker prospect',
    description: 'Add an organization contact to the speaker sourcing pipeline.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['personId', 'stage'],
    emits: ['crm.pipeline-enrolled'],
  },
  {
    name: 'crm.pipeline.move',
    title: 'Move speaker prospect',
    description: 'Move a speaker prospect to another sourcing stage and record the transition.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['entryId', 'stage'],
    emits: ['crm.pipeline-moved'],
  },
  {
    name: 'crm.pipeline.add-note',
    title: 'Add pipeline note',
    description: 'Add a timestamped internal note to a speaker sourcing card.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['entryId', 'body'],
    emits: ['crm.pipeline-note-added'],
  },
  {
    name: 'crm.outreach.queue',
    title: 'Queue CRM outreach',
    description: 'Queue one personalized message for each selected organization contact.',
    kind: 'command',
    scopes: ['communications:write'],
    risk: 'external',
    agentPolicy: 'propose_only',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['personIds', 'subject', 'body'],
    emits: ['crm.outreach-queued'],
  },
  {
    name: 'person.import',
    title: 'Import people',
    description: 'Import speaker profiles into the active event and skip existing email addresses.',
    kind: 'command',
    scopes: ['people:write', 'participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['people'],
    emits: ['person.created', 'participation.created', 'people.imported'],
  },
  {
    name: 'person.update',
    title: 'Update person',
    description: 'Update contact or public profile fields for a person.',
    kind: 'command',
    scopes: ['people:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['personId'],
    emits: ['person.updated'],
  },
  {
    name: 'asset.register',
    title: 'Register uploaded asset',
    description: 'Attach uploaded file metadata to an active-event record.',
    kind: 'command',
    scopes: ['assets:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: true,
    requiredInput: [
      'ownerType',
      'ownerId',
      'kind',
      'filename',
      'contentType',
      'sizeBytes',
      'storageKey',
    ],
    emits: ['asset.registered', 'requirement.status-changed'],
  },
  {
    name: 'asset.comment',
    title: 'Comment on file',
    description: 'Add an attributed comment to an uploaded file.',
    kind: 'command',
    scopes: ['assets:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['assetId', 'body'],
    emits: ['asset.commented'],
  },
  {
    name: 'participation.set-status',
    title: 'Set participation status',
    description: 'Move a participant through the invitation and confirmation lifecycle.',
    kind: 'command',
    scopes: ['participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['participationId', 'status'],
    emits: ['participation.status-changed'],
  },
  {
    name: 'participation.update-logistics',
    title: 'Update speaker logistics',
    description: 'Store private travel and logistics notes for an event participant.',
    kind: 'command',
    scopes: ['participations:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['participationId', 'internalNotes'],
    emits: ['participation.logistics-updated'],
  },
  {
    name: 'requirement.create',
    title: 'Create participant task',
    description: 'Create a dated task and assign it to selected event participants.',
    kind: 'command',
    scopes: ['requirements:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['label', 'dueAt', 'participationIds'],
    emits: ['requirement.created', 'requirement.assigned'],
  },
  {
    name: 'requirement.set-status',
    title: 'Review requirement',
    description: 'Submit, approve, waive, or request revision on a readiness requirement.',
    kind: 'command',
    scopes: ['requirements:write'],
    risk: 'internal',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['requirementInstanceId', 'status'],
    emits: ['requirement.status-changed', 'participation.readiness-changed'],
  },
  {
    name: 'requirement.process-reminders',
    title: 'Process automatic task reminders',
    description: 'Queue due reminder messages for incomplete speaker tasks.',
    kind: 'command',
    scopes: ['requirements:write'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['at'],
    emits: ['requirement.reminder-queued'],
  },
  {
    name: 'portal.update-profile',
    title: 'Update participant profile',
    description: 'Allow a participant to update their own public profile fields.',
    kind: 'command',
    scopes: ['portal:write'],
    risk: 'internal',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['participationId'],
    emits: ['participant.profile-updated'],
  },
  {
    name: 'portal-resource.create',
    title: 'Create speaker resource',
    description: 'Create a draft or published resource page for the speaker portal.',
    kind: 'command',
    scopes: ['portal:write'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['title'],
    emits: ['portal-resource.created'],
  },
  {
    name: 'portal-resource.update',
    title: 'Update speaker resource',
    description: 'Update, publish, or archive a speaker portal resource page.',
    kind: 'command',
    scopes: ['portal:write'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['resourceId'],
    emits: ['portal-resource.updated'],
  },
  {
    name: 'schedule.place-session',
    title: 'Place session',
    description: 'Assign an unscheduled session to a room and start time.',
    kind: 'command',
    scopes: ['schedule:draft'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['sessionId', 'roomId', 'startsAt'],
    emits: ['schedule.session-placed'],
  },
  {
    name: 'schedule.move-session',
    title: 'Move session',
    description: 'Move a session to another room or start time and recalculate conflicts.',
    kind: 'command',
    scopes: ['schedule:draft'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['placementId', 'roomId', 'startsAt'],
    emits: ['schedule.session-moved'],
  },
  {
    name: 'schedule.auto-place',
    title: 'Auto-place sessions',
    description: 'Place unscheduled sessions into the earliest conflict-free rooms and times.',
    kind: 'command',
    scopes: ['schedule:draft'],
    risk: 'public',
    agentPolicy: 'propose_only',
    reversible: true,
    supportsDryRun: true,
    requiredInput: [],
    emits: ['schedule.sessions-auto-placed'],
  },
  {
    name: 'schedule.publish',
    title: 'Publish schedule',
    description: 'Publish the current conflict-free schedule as a new immutable version.',
    kind: 'command',
    scopes: ['schedule:publish'],
    risk: 'public',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: [],
    emits: ['schedule.published'],
  },
  {
    name: 'campaign.send-portal-invite',
    title: 'Send speaker portal invitation',
    description:
      'Queue one personalized speaker portal invitation and record it in communications history.',
    kind: 'command',
    scopes: ['communications:send'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['participationId'],
    emits: ['campaign.sent'],
  },
  {
    name: 'campaign.create-draft',
    title: 'Draft campaign',
    description: 'Create a targeted message draft with a calculated audience.',
    kind: 'command',
    scopes: ['communications:draft'],
    risk: 'internal',
    agentPolicy: 'execute',
    reversible: true,
    supportsDryRun: true,
    requiredInput: ['name', 'subject', 'body', 'audience'],
    emits: ['campaign.drafted'],
  },
  {
    name: 'campaign.submit',
    title: 'Submit campaign',
    description: 'Submit a campaign for human approval.',
    kind: 'command',
    scopes: ['communications:draft'],
    risk: 'internal',
    agentPolicy: 'execute',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['campaignId'],
    emits: ['campaign.submitted'],
  },
  {
    name: 'campaign.approve',
    title: 'Approve campaign',
    description: 'Approve an exact campaign version and recipient set.',
    kind: 'command',
    scopes: ['communications:approve'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['campaignId'],
    emits: ['campaign.approved'],
  },
  {
    name: 'campaign.send',
    title: 'Send campaign',
    description: 'Record and enqueue an approved campaign for delivery.',
    kind: 'command',
    scopes: ['communications:send'],
    risk: 'external',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: true,
    requiredInput: ['campaignId'],
    emits: ['campaign.sent'],
  },
  {
    name: 'change-set.create',
    title: 'Create change set',
    description: 'Create a reviewable proposal containing one or more operations.',
    kind: 'command',
    scopes: ['changes:propose'],
    risk: 'internal',
    agentPolicy: 'execute',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['title', 'operations'],
    emits: ['change-set.created'],
  },
  {
    name: 'change-set.approve',
    title: 'Approve change set',
    description: 'Approve a validated proposal for commit.',
    kind: 'command',
    scopes: ['changes:approve'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: true,
    supportsDryRun: false,
    requiredInput: ['changeSetId'],
    emits: ['change-set.approved'],
  },
  {
    name: 'change-set.reject',
    title: 'Reject change set',
    description: 'Reject a proposed change set without applying its operations.',
    kind: 'command',
    scopes: ['changes:approve'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['changeSetId'],
    emits: ['change-set.rejected'],
  },
  {
    name: 'change-set.commit',
    title: 'Commit change set',
    description: 'Revalidate and atomically apply an approved proposal.',
    kind: 'command',
    scopes: ['changes:commit'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: ['changeSetId'],
    emits: ['change-set.committed', 'change-set.stale'],
  },
  {
    name: 'workspace.reset-demo',
    title: 'Reset demo workspace',
    description: 'Replace the workspace with the deterministic demonstration dataset.',
    kind: 'command',
    scopes: ['workspace:admin'],
    risk: 'administrative',
    agentPolicy: 'denied',
    reversible: false,
    supportsDryRun: false,
    requiredInput: [],
    emits: ['workspace.reset'],
  },
] as const satisfies readonly OperationDefinition[]

export type OperationName = (typeof operationManifest)[number]['name']

export function operationDefinition(name: string) {
  return operationManifest.find((operation) => operation.name === name)
}
