import type {
  Asset,
  Campaign,
  CampaignDelivery,
  EvaluationPlan,
  Integration,
  Participation,
  Person,
  Placement,
  PortalResource,
  ReviewDecision,
  Reviewer,
  ReviewerAssignment,
  ReviewerTeam,
  RequirementDefinition,
  RequirementInstance,
  Room,
  ScheduleRelease,
  Scorecard,
  Session,
  Submission,
  SubmissionForm,
  SubmissionFormField,
  SubmissionReceiptDelivery,
  Track,
  WorkspaceState,
} from './types.ts'

const seededAt = '2026-08-07T14:00:00.000Z'
const eventId = 'evt_nyc_2026'

const peopleInput = [
  ['Robin', 'Sloan', 'robin@axiom.dev', 'Axiom', 'Founder', 'Austin, TX', 'America/Chicago'],
  [
    'Cameron',
    'Lee',
    'cameron@northstar.ai',
    'Northstar',
    'VP, Product',
    'New York, NY',
    'America/New_York',
  ],
  [
    'Jordan',
    'Bell',
    'jordan@commonthread.org',
    'Common Thread',
    'Research Lead',
    'Toronto, ON',
    'America/Toronto',
  ],
  [
    'Taylor',
    'Reed',
    'taylor@foil.studio',
    'Foil Studio',
    'Design Partner',
    'London, UK',
    'Europe/London',
  ],
  [
    'Morgan',
    'Shah',
    'morgan@relay.run',
    'Relay',
    'Co-founder',
    'San Francisco, CA',
    'America/Los_Angeles',
  ],
  ['Casey', 'Morris', 'casey@fieldwork.co', 'Fieldwork', 'COO', 'Chicago, IL', 'America/Chicago'],
  [
    'Riley',
    'Chen',
    'riley@studiozero.com',
    'Studio Zero',
    'Creative Director',
    'Los Angeles, CA',
    'America/Los_Angeles',
  ],
  [
    'Avery',
    'Patel',
    'avery@frame.work',
    'Frame',
    'Engineering Lead',
    'Seattle, WA',
    'America/Los_Angeles',
  ],
  ['Quinn', 'Baker', 'quinn@signalpath.io', 'Signal Path', 'CEO', 'Boston, MA', 'America/New_York'],
  [
    'Parker',
    'Diaz',
    'parker@grain.com',
    'Grain',
    'Head of Growth',
    'Miami, FL',
    'America/New_York',
  ],
  [
    'Rowan',
    'Kim',
    'rowan@parallel.systems',
    'Parallel',
    'Staff Engineer',
    'Brooklyn, NY',
    'America/New_York',
  ],
  [
    'Skyler',
    'Nguyen',
    'skyler@horizon.vc',
    'Horizon Ventures',
    'Partner',
    'Denver, CO',
    'America/Denver',
  ],
  ['Jamie', 'Brooks', 'jamie@applied.fm', 'Applied', 'Host', 'Nashville, TN', 'America/Chicago'],
  [
    'Drew',
    'Foster',
    'drew@kindred.health',
    'Kindred',
    'Product Director',
    'Portland, OR',
    'America/Los_Angeles',
  ],
  ['Reese', 'Stone', 'reese@motif.tools', 'Motif', 'Founder', 'New York, NY', 'America/New_York'],
  [
    'Sage',
    'Wright',
    'sage@wavelength.bio',
    'Wavelength',
    'AI Lead',
    'Cambridge, MA',
    'America/New_York',
  ],
] as const

const bios = [
  'Builds practical systems for small teams adopting AI without adding operational drag.',
  'Leads product teams through complex platform shifts and the workflows around them.',
  'Studies how people collaborate with adaptive software in high-stakes environments.',
  'Designs calm, legible interfaces for tools that people use all day.',
]

const people: Person[] = peopleInput.map((person, index) => ({
  id: `per_${String(index + 1).padStart(3, '0')}`,
  firstName: person[0],
  lastName: person[1],
  email: person[2],
  company: person[3],
  title: person[4],
  city: person[5],
  timezone: person[6],
  bio: bios[index % bios.length],
  avatarUrl: `https://assets.ui.sh/avatars/${(index % 12) + 1}.webp`,
  tags: index % 3 === 0 ? ['returning speaker'] : index % 4 === 0 ? ['vip'] : [],
  createdAt: seededAt,
  updatedAt: seededAt,
  version: 1,
}))

const participationStatuses: Participation['status'][] = [
  'confirmed',
  'confirmed',
  'invited',
  'confirmed',
  'confirmed',
  'invited',
  'confirmed',
  'confirmed',
  'prospect',
  'confirmed',
  'invited',
  'confirmed',
  'confirmed',
  'confirmed',
  'invited',
  'confirmed',
]

const participations: Participation[] = people.map((person, index) => ({
  id: `par_${String(index + 1).padStart(3, '0')}`,
  eventId,
  personId: person.id,
  roles:
    index === 2 || index === 8
      ? ['moderator']
      : index === 7 || index === 15
        ? ['workshop_lead']
        : index % 5 === 0
          ? ['panelist']
          : ['speaker'],
  status: participationStatuses[index],
  sessionIds: [],
  internalNotes: index === 4 ? 'Assistant coordinates all schedule changes.' : '',
  publicTitle: person.title,
  publicCompany: person.company,
  confirmedAt:
    participationStatuses[index] === 'confirmed'
      ? `2026-07-${String(12 + index).padStart(2, '0')}T15:00:00.000Z`
      : null,
  updatedAt: seededAt,
  version: 1,
}))

const requirementDefinitions: RequirementDefinition[] = [
  {
    id: 'req_confirm',
    eventId,
    label: 'Confirm participation',
    description: 'Accept the invitation and confirm attendance.',
    kind: 'confirmation',
    dueAt: '2026-08-21T21:00:00.000Z',
    required: true,
  },
  {
    id: 'req_bio',
    eventId,
    label: 'Speaker bio',
    description: 'Provide a public bio of no more than 600 characters.',
    kind: 'text',
    dueAt: '2026-09-04T21:00:00.000Z',
    required: true,
  },
  {
    id: 'req_headshot',
    eventId,
    label: 'Headshot',
    description: 'Upload a square, high-resolution public headshot.',
    kind: 'file',
    dueAt: '2026-09-04T21:00:00.000Z',
    required: true,
  },
  {
    id: 'req_release',
    eventId,
    label: 'Recording release',
    description: 'Review and sign the event recording release.',
    kind: 'approval',
    dueAt: '2026-09-11T21:00:00.000Z',
    required: true,
  },
  {
    id: 'req_av',
    eventId,
    label: 'AV requirements',
    description: 'Tell the production team what you need on stage.',
    kind: 'form',
    dueAt: '2026-09-18T21:00:00.000Z',
    required: true,
  },
  {
    id: 'req_slides',
    eventId,
    label: 'Final slides',
    description: 'Upload the final presentation deck.',
    kind: 'file',
    dueAt: '2026-09-25T21:00:00.000Z',
    required: true,
  },
]

const statusByIndex = (
  participantIndex: number,
  requirementIndex: number,
): RequirementInstance['status'] => {
  if (requirementIndex === 0)
    return participationStatuses[participantIndex] === 'confirmed' ? 'approved' : 'not_started'
  const score = (participantIndex * 2 + requirementIndex) % 7
  if (score <= 2) return 'approved'
  if (score === 3) return 'submitted'
  if (score === 4) return 'revision_requested'
  return 'not_started'
}

const requirementInstances: RequirementInstance[] = participations.flatMap(
  (participation, participantIndex) =>
    requirementDefinitions.map((definition, requirementIndex) => {
      const status = statusByIndex(participantIndex, requirementIndex)
      return {
        id: `rqi_${participantIndex + 1}_${requirementIndex + 1}`,
        definitionId: definition.id,
        participationId: participation.id,
        status,
        value:
          definition.id === 'req_av' && status !== 'not_started'
            ? participantIndex % 2 === 0
              ? 'Confidence monitor and handheld microphone.'
              : 'Standard stage setup.'
            : '',
        submittedAt: status === 'submitted' || status === 'approved' ? seededAt : null,
        reviewedAt: status === 'approved' ? seededAt : null,
        updatedAt: seededAt,
        version: 1,
      }
    }),
)

const submissionForms: SubmissionForm[] = [
  {
    id: 'frm_cfp_2026',
    eventId,
    name: 'AIE NYC call for proposals',
    slug: 'aie-nyc-2026-cfp',
    title: 'Share what you learned building with AI',
    description:
      'Submit a practical talk or workshop for AIE NYC. We value specific lessons, honest tradeoffs, and ideas attendees can use.',
    status: 'open',
    allowedKinds: ['abstract'],
    opensAt: '2026-07-13T13:00:00.000Z',
    closesAt: '2026-08-28T03:59:00.000Z',
    confirmationMessage:
      'Your proposal is in. The program team will contact you after committee review.',
    updatedAt: seededAt,
    version: 3,
  },
  {
    id: 'frm_guaranteed_2026',
    eventId,
    name: 'Guaranteed session details',
    slug: 'aie-nyc-2026-guaranteed-session',
    title: 'Tell us about your confirmed session',
    description:
      'For invited speakers and partners with a guaranteed program slot. These details go directly to the program team.',
    status: 'open',
    allowedKinds: ['guaranteed_session'],
    opensAt: '2026-07-13T13:00:00.000Z',
    closesAt: '2026-09-04T03:59:00.000Z',
    confirmationMessage: 'Thanks—your session details are ready for the program team.',
    updatedAt: seededAt,
    version: 2,
  },
]

const submissionFormFields: SubmissionFormField[] = [
  {
    id: 'fld_cfp_first_name',
    formId: 'frm_cfp_2026',
    key: 'first_name',
    label: 'First name',
    description: '',
    kind: 'short_text',
    purpose: 'first_name',
    required: true,
    options: [],
    placeholder: 'Ada',
    sortOrder: 10,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_last_name',
    formId: 'frm_cfp_2026',
    key: 'last_name',
    label: 'Last name',
    description: '',
    kind: 'short_text',
    purpose: 'last_name',
    required: true,
    options: [],
    placeholder: 'Lovelace',
    sortOrder: 20,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_email',
    formId: 'frm_cfp_2026',
    key: 'email',
    label: 'Email',
    description: 'We use this to identify your submission in our records.',
    kind: 'email',
    purpose: 'email',
    required: true,
    options: [],
    placeholder: 'ada@example.com',
    sortOrder: 30,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_company',
    formId: 'frm_cfp_2026',
    key: 'company',
    label: 'Company or organization',
    description: '',
    kind: 'short_text',
    purpose: 'company',
    required: false,
    options: [],
    placeholder: 'Analytical Engines',
    sortOrder: 40,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_job_title',
    formId: 'frm_cfp_2026',
    key: 'job_title',
    label: 'Role',
    description: '',
    kind: 'short_text',
    purpose: 'job_title',
    required: false,
    options: [],
    placeholder: 'Research lead',
    sortOrder: 50,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_bio',
    formId: 'frm_cfp_2026',
    key: 'biography',
    label: 'Short biography',
    description: 'Write this in the third person. 600 characters maximum.',
    kind: 'long_text',
    purpose: 'biography',
    required: true,
    options: [],
    placeholder: 'Tell attendees what makes your perspective useful.',
    sortOrder: 60,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_title',
    formId: 'frm_cfp_2026',
    key: 'proposal_title',
    label: 'Session title',
    description: 'Keep it specific and understandable without extra context.',
    kind: 'short_text',
    purpose: 'proposal_title',
    required: true,
    options: [],
    placeholder: 'What we learned shipping…',
    sortOrder: 70,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_abstract',
    formId: 'frm_cfp_2026',
    key: 'abstract',
    label: 'Abstract',
    description: 'Explain the problem, your approach, and what attendees will take away.',
    kind: 'long_text',
    purpose: 'abstract',
    required: true,
    options: [],
    placeholder: 'In this session…',
    sortOrder: 80,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_format',
    formId: 'frm_cfp_2026',
    key: 'session_format',
    label: 'Preferred format',
    description: '',
    kind: 'select',
    purpose: 'session_format',
    required: true,
    options: [
      { value: 'talk', label: '30-minute talk' },
      { value: 'panel', label: '45-minute panel' },
      { value: 'workshop', label: '75-minute workshop' },
    ],
    placeholder: 'Choose a format',
    sortOrder: 90,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_track',
    formId: 'frm_cfp_2026',
    key: 'track',
    label: 'Best-fit track',
    description: 'The program team may move accepted sessions to another track.',
    kind: 'select',
    purpose: 'track',
    required: true,
    options: [
      { value: 'trk_frontier', label: 'Frontier' },
      { value: 'trk_build', label: 'Build' },
      { value: 'trk_operate', label: 'Operate' },
      { value: 'trk_society', label: 'Society' },
    ],
    placeholder: 'Choose a track',
    sortOrder: 100,
    visibleWhen: null,
  },
  {
    id: 'fld_cfp_workshop_outline',
    formId: 'frm_cfp_2026',
    key: 'workshop_outline',
    label: 'Workshop plan',
    description: 'Describe the hands-on exercise, prerequisites, and intended outcome.',
    kind: 'long_text',
    purpose: 'custom',
    required: true,
    options: [],
    placeholder: 'Attendees will work through…',
    sortOrder: 110,
    visibleWhen: { fieldId: 'fld_cfp_format', operator: 'equals', value: 'workshop' },
  },
  {
    id: 'fld_cfp_video',
    formId: 'frm_cfp_2026',
    key: 'video_url',
    label: 'Optional introduction video',
    description:
      'Share a short public or unlisted video that helps reviewers understand your style.',
    kind: 'url',
    purpose: 'custom',
    required: false,
    options: [],
    placeholder: 'https://…',
    sortOrder: 120,
    visibleWhen: null,
  },
  ...[
    ['first_name', 'First name', 'first_name', 'short_text'],
    ['last_name', 'Last name', 'last_name', 'short_text'],
    ['email', 'Email', 'email', 'email'],
    ['company', 'Company or organization', 'company', 'short_text'],
    ['job_title', 'Role', 'job_title', 'short_text'],
    ['biography', 'Short biography', 'biography', 'long_text'],
    ['proposal_title', 'Session title', 'proposal_title', 'short_text'],
    ['abstract', 'Session description', 'abstract', 'long_text'],
    ['session_format', 'Session format', 'session_format', 'select'],
    ['track', 'Program track', 'track', 'select'],
  ].map((field, index) => ({
    id: `fld_guaranteed_${field[0]}`,
    formId: 'frm_guaranteed_2026',
    key: field[0],
    label: field[1],
    description: '',
    kind: field[3] as SubmissionFormField['kind'],
    purpose: field[2] as SubmissionFormField['purpose'],
    required: !['company', 'job_title'].includes(field[0]),
    options:
      field[0] === 'session_format'
        ? [
            { value: 'talk', label: '30-minute talk' },
            { value: 'panel', label: '45-minute panel' },
            { value: 'workshop', label: '75-minute workshop' },
            { value: 'keynote', label: '40-minute keynote' },
          ]
        : field[0] === 'track'
          ? [
              { value: 'trk_frontier', label: 'Frontier' },
              { value: 'trk_build', label: 'Build' },
              { value: 'trk_operate', label: 'Operate' },
              { value: 'trk_society', label: 'Society' },
            ]
          : [],
    placeholder: '',
    sortOrder: (index + 1) * 10,
    visibleWhen: null,
  })),
]

const submissionAnswers = (
  firstName: string,
  lastName: string,
  email: string,
  company: string,
  jobTitle: string,
  biography: string,
  proposalTitle: string,
  abstract: string,
  sessionFormat: 'talk' | 'panel' | 'workshop' | 'keynote',
  track: string,
  extra: Record<string, string> = {},
) => ({
  first_name: firstName,
  last_name: lastName,
  email,
  company,
  job_title: jobTitle,
  biography,
  proposal_title: proposalTitle,
  abstract,
  session_format: sessionFormat,
  track,
  ...extra,
})

const submissions: Submission[] = [
  {
    id: 'sub_001',
    eventId,
    formId: 'frm_cfp_2026',
    kind: 'abstract',
    status: 'accepted',
    answers: submissionAnswers(
      'Robin',
      'Sloan',
      'robin@axiom.dev',
      'Axiom',
      'Founder',
      bios[0],
      'Opening the useful frontier',
      'Where the past year of capability actually landed, and which of it survived contact with real users.',
      'keynote',
      'trk_frontier',
      { video_url: 'https://video.example.com/robin-intro' },
    ),
    assetIds: ['ast_001'],
    submittedAt: '2026-07-20T16:20:00.000Z',
    decidedAt: '2026-07-30T15:00:00.000Z',
    convertedParticipationId: 'par_001',
    convertedSessionId: 'ses_001',
    createdAt: '2026-07-18T15:00:00.000Z',
    updatedAt: '2026-07-30T15:00:00.000Z',
    version: 3,
  },
  {
    id: 'sub_002',
    eventId,
    formId: 'frm_cfp_2026',
    kind: 'abstract',
    status: 'in_review',
    answers: submissionAnswers(
      'Mina',
      'Okafor',
      'mina@plainspoken.systems',
      'Plainspoken Systems',
      'Principal engineer',
      'Mina builds observable AI systems for public-interest organizations.',
      'The boring parts of trustworthy agents',
      'A production teardown of retries, review queues, and provenance in an agent workflow used every day.',
      'talk',
      'trk_operate',
      { video_url: 'https://video.example.com/mina-agents' },
    ),
    assetIds: ['ast_002'],
    submittedAt: '2026-08-01T18:42:00.000Z',
    decidedAt: null,
    convertedParticipationId: null,
    convertedSessionId: null,
    createdAt: '2026-07-31T20:00:00.000Z',
    updatedAt: '2026-08-06T16:10:00.000Z',
    version: 2,
  },
  {
    id: 'sub_003',
    eventId,
    formId: 'frm_guaranteed_2026',
    kind: 'guaranteed_session',
    status: 'submitted',
    answers: submissionAnswers(
      'Noah',
      'Williams',
      'noah@orbitlabs.com',
      'Orbit Labs',
      'Chief product officer',
      'Noah leads the product organization at Orbit Labs.',
      'A candid year in enterprise AI',
      'The decisions, failed pilots, and operating changes behind one company’s first year deploying AI broadly.',
      'keynote',
      'trk_operate',
    ),
    assetIds: [],
    submittedAt: '2026-08-05T14:30:00.000Z',
    decidedAt: null,
    convertedParticipationId: null,
    convertedSessionId: null,
    createdAt: '2026-08-05T14:12:00.000Z',
    updatedAt: '2026-08-05T14:30:00.000Z',
    version: 2,
  },
  {
    id: 'sub_004',
    eventId,
    formId: 'frm_cfp_2026',
    kind: 'abstract',
    status: 'rejected',
    answers: submissionAnswers(
      'Emery',
      'Jones',
      'emery@example.com',
      'Independent',
      'Consultant',
      'Emery advises early-stage teams.',
      'AI will change everything',
      'A broad survey of recent artificial intelligence news and trends.',
      'talk',
      'trk_frontier',
    ),
    assetIds: [],
    submittedAt: '2026-07-24T19:10:00.000Z',
    decidedAt: '2026-08-04T15:00:00.000Z',
    convertedParticipationId: null,
    convertedSessionId: null,
    createdAt: '2026-07-24T18:50:00.000Z',
    updatedAt: '2026-08-04T15:00:00.000Z',
    version: 3,
  },
  {
    id: 'sub_005',
    eventId,
    formId: 'frm_cfp_2026',
    kind: 'abstract',
    status: 'submitted',
    answers: submissionAnswers(
      'Priya',
      'Raman',
      'priya@craftwork.dev',
      'Craftwork',
      'Design engineer',
      'Priya prototypes interfaces for software with uncertain outputs.',
      'Designing the human handoff',
      'Five interface patterns that make escalation and human approval feel like part of the product.',
      'talk',
      'trk_build',
    ),
    assetIds: [],
    submittedAt: '2026-08-07T12:10:00.000Z',
    decidedAt: null,
    convertedParticipationId: null,
    convertedSessionId: null,
    createdAt: '2026-08-06T22:00:00.000Z',
    updatedAt: '2026-08-07T12:10:00.000Z',
    version: 2,
  },
  {
    id: 'sub_006',
    eventId,
    formId: 'frm_cfp_2026',
    kind: 'abstract',
    status: 'draft',
    answers: submissionAnswers(
      'Leo',
      'Martin',
      'leo@littleloops.dev',
      'Little Loops',
      'Founder',
      'Leo teaches small teams to automate repetitive operating work.',
      'Automation you can understand',
      '',
      'workshop',
      'trk_build',
    ),
    assetIds: [],
    submittedAt: null,
    decidedAt: null,
    convertedParticipationId: null,
    convertedSessionId: null,
    createdAt: '2026-08-07T13:30:00.000Z',
    updatedAt: '2026-08-07T13:30:00.000Z',
    version: 1,
  },
]

const submissionReceiptDeliveries: SubmissionReceiptDelivery[] = [
  {
    id: 'rcp_001',
    submissionId: 'sub_005',
    eventId,
    formId: 'frm_cfp_2026',
    recipientName: 'Priya Raman',
    recipientEmail: 'priya@craftwork.dev',
    subject: 'We received your proposal for AIE NYC 2026',
    body: [
      'Hi Priya,',
      '',
      'We received “Designing the human handoff” for AIE NYC 2026.',
      'Your proposal is in. The program team will contact you after committee review.',
      '',
      'Reference: sub_005',
      '',
      'Keep this reference if you need to follow up with the program team.',
    ].join('\n'),
    status: 'pending_provider',
    provider: null,
    providerMessageId: null,
    attemptCount: 0,
    lastError: null,
    createdAt: '2026-08-07T12:10:00.000Z',
    updatedAt: '2026-08-07T12:10:00.000Z',
    version: 1,
  },
]

const assets: Asset[] = [
  {
    id: 'ast_001',
    eventId,
    owner: { type: 'submission', id: 'sub_001' },
    kind: 'video',
    filename: 'robin-sloan-introduction.mp4',
    contentType: 'video/mp4',
    sizeBytes: 18_420_000,
    storageKey: 'demo/submissions/sub_001/robin-sloan-introduction.mp4',
    createdAt: '2026-07-20T16:18:00.000Z',
  },
  {
    id: 'ast_002',
    eventId,
    owner: { type: 'submission', id: 'sub_002' },
    kind: 'supporting_document',
    filename: 'agent-reliability-case-study.pdf',
    contentType: 'application/pdf',
    sizeBytes: 2_842_000,
    storageKey: 'demo/submissions/sub_002/agent-reliability-case-study.pdf',
    createdAt: '2026-08-01T18:40:00.000Z',
  },
]

const portalResources: PortalResource[] = [
  {
    id: 'por_speaker_guide',
    eventId,
    title: 'Speaker guide',
    summary: 'Arrival, green room, and production notes for your event days.',
    kind: 'guide',
    body: 'Arrival\nCheck in at Building 77 at least 45 minutes before your first session. Bring a photo ID for the venue desk.\n\nGreen room\nThe speaker green room is on the third floor. Program staff can review slides, microphones, and accessibility needs with you there.\n\nOn stage\nA confidence monitor, presentation remote, and water will be ready. Please keep the final five minutes open for audience questions.',
    embedHtml: null,
    status: 'published',
    sortOrder: 10,
    updatedAt: '2026-08-07T14:00:00.000Z',
    version: 1,
  },
  {
    id: 'por_venue_card',
    eventId,
    title: 'Venue quick card',
    summary: 'A safe embedded briefing you can keep open on arrival.',
    kind: 'html_embed',
    body: '',
    embedHtml:
      '<article><h2>Brooklyn Navy Yard</h2><p>Building 77, first-floor check-in.</p><ul><li>Doors open at 8:00 AM.</li><li>Bring a photo ID.</li><li>Ask for the AIE speaker desk.</li></ul></article>',
    status: 'published',
    sortOrder: 20,
    updatedAt: '2026-08-07T14:00:00.000Z',
    version: 1,
  },
]

const reviewers: Reviewer[] = [
  {
    id: 'rev_001',
    eventId,
    name: 'Elena Vasquez',
    email: 'elena@aie.example',
    status: 'active',
    createdAt: '2026-07-14T15:00:00.000Z',
    version: 1,
  },
  {
    id: 'rev_002',
    eventId,
    name: 'Marcus Lin',
    email: 'marcus@aie.example',
    status: 'active',
    createdAt: '2026-07-14T15:00:00.000Z',
    version: 1,
  },
  {
    id: 'rev_003',
    eventId,
    name: 'Samira Cole',
    email: 'samira@aie.example',
    status: 'active',
    createdAt: '2026-07-14T15:00:00.000Z',
    version: 1,
  },
]

const reviewerTeams: ReviewerTeam[] = [
  {
    id: 'rvt_program',
    eventId,
    name: 'Program committee',
    reviewerIds: reviewers.map((reviewer) => reviewer.id),
    version: 1,
  },
]

const evaluationPlans: EvaluationPlan[] = [
  {
    id: 'evp_cfp_2026',
    eventId,
    formId: 'frm_cfp_2026',
    name: 'AIE NYC proposal review',
    reviewerTeamId: 'rvt_program',
    submissionKinds: ['abstract'],
    blindReview: false,
    rounds: [
      {
        id: 'rnd_program_review',
        name: 'Program committee review',
        order: 1,
        reviewersPerSubmission: 2,
        minimumCompletedReviews: 2,
      },
      {
        id: 'rnd_finalist_review',
        name: 'Finalist review',
        order: 2,
        reviewersPerSubmission: 2,
        minimumCompletedReviews: 2,
      },
    ],
    criteria: [
      {
        id: 'crt_relevance',
        label: 'Relevance',
        description: 'The proposal fits the audience and this year’s program.',
        minimum: 1,
        maximum: 5,
        weight: 1,
      },
      {
        id: 'crt_specificity',
        label: 'Specificity',
        description: 'The proposal is grounded in concrete experience rather than broad claims.',
        minimum: 1,
        maximum: 5,
        weight: 1.25,
      },
      {
        id: 'crt_takeaway',
        label: 'Attendee value',
        description: 'Attendees will leave with a useful idea, method, or decision framework.',
        minimum: 1,
        maximum: 5,
        weight: 1.5,
      },
    ],
    version: 1,
  },
]

const assignmentInput = [
  ['rva_001', 'sub_001', 'rev_001', 'completed'],
  ['rva_002', 'sub_001', 'rev_002', 'completed'],
  ['rva_003', 'sub_002', 'rev_001', 'completed'],
  ['rva_004', 'sub_002', 'rev_003', 'completed'],
  ['rva_005', 'sub_004', 'rev_002', 'completed'],
  ['rva_006', 'sub_004', 'rev_003', 'completed'],
  ['rva_007', 'sub_005', 'rev_001', 'assigned'],
  ['rva_008', 'sub_005', 'rev_002', 'assigned'],
] as const

const reviewerAssignments: ReviewerAssignment[] = assignmentInput.map((assignment) => ({
  id: assignment[0],
  eventId,
  evaluationPlanId: 'evp_cfp_2026',
  roundId: 'rnd_program_review',
  submissionId: assignment[1],
  reviewerId: assignment[2],
  status: assignment[3],
  dueAt: '2026-08-12T03:59:00.000Z',
  updatedAt: seededAt,
  version: assignment[3] === 'completed' ? 2 : 1,
}))

const scorecards: Scorecard[] = [
  ['sco_001', 'rva_001', 5, 5, 5, 'strong_accept', 'Excellent opening session.'],
  ['sco_002', 'rva_002', 5, 4, 5, 'strong_accept', 'Clear, timely, and grounded.'],
  ['sco_003', 'rva_003', 5, 5, 4, 'strong_accept', 'The operational detail is unusually useful.'],
  ['sco_004', 'rva_004', 4, 5, 5, 'accept', 'Strong fit; ask for one concrete failure story.'],
  ['sco_005', 'rva_005', 2, 1, 2, 'reject', 'Too broad for this program.'],
  ['sco_006', 'rva_006', 2, 2, 2, 'strong_reject', 'Needs a more specific claim and takeaway.'],
].map((scorecard) => ({
  id: scorecard[0] as string,
  assignmentId: scorecard[1] as string,
  scores: {
    crt_relevance: scorecard[2] as number,
    crt_specificity: scorecard[3] as number,
    crt_takeaway: scorecard[4] as number,
  },
  recommendation: scorecard[5] as Scorecard['recommendation'],
  comments: scorecard[6] as string,
  submittedAt: seededAt,
  updatedAt: seededAt,
  version: 1,
}))

const reviewDecisions: ReviewDecision[] = [
  {
    id: 'rde_001',
    eventId,
    submissionId: 'sub_001',
    decision: 'accepted',
    reason: 'A strong, practical opening for the program.',
    decidedBy: { type: 'staff', id: 'usr_alex', name: 'Alex Morgan' },
    decidedAt: '2026-07-30T15:00:00.000Z',
    version: 1,
  },
  {
    id: 'rde_002',
    eventId,
    submissionId: 'sub_004',
    decision: 'rejected',
    reason: 'The proposal is too broad for this year’s program.',
    decidedBy: { type: 'staff', id: 'usr_alex', name: 'Alex Morgan' },
    decidedAt: '2026-08-04T15:00:00.000Z',
    version: 1,
  },
]

const tracks: Track[] = [
  { id: 'trk_frontier', eventId, name: 'Frontier', color: 'emerald' },
  { id: 'trk_build', eventId, name: 'Build', color: 'sky' },
  { id: 'trk_operate', eventId, name: 'Operate', color: 'amber' },
  { id: 'trk_society', eventId, name: 'Society', color: 'violet' },
]

const rooms: Room[] = [
  { id: 'rom_main', eventId, name: 'Main stage', capacity: 420 },
  { id: 'rom_studio', eventId, name: 'Studio', capacity: 150 },
  { id: 'rom_workshop', eventId, name: 'Workshop', capacity: 72 },
]

const sessionInputs = [
  [
    'ses_001',
    'Opening the useful frontier',
    'keynote',
    'trk_frontier',
    [0],
    40,
    380,
    'Where the past year of capability actually landed, and which of it survived contact with real users.',
  ],
  [
    'ses_002',
    'The new shape of a product team',
    'panel',
    'trk_operate',
    [1, 2, 4],
    45,
    130,
    'Three teams that reorganized around fast evaluation describe what they stopped doing to make room.',
  ],
  [
    'ses_003',
    'Interfaces for uncertain systems',
    'talk',
    'trk_build',
    [3],
    30,
    105,
    'Patterns for showing confidence, cost, and provenance without burying the person in caveats.',
  ],
  [
    'ses_004',
    'From prototype to dependable workflow',
    'workshop',
    'trk_build',
    [7, 10],
    75,
    66,
    'Hands-on: take a demo that works once and add the retries, budgets, and checks it needs to run daily.',
  ],
  [
    'ses_005',
    'Buying, building, and the space between',
    'panel',
    'trk_operate',
    [5, 8, 11],
    45,
    118,
    'How four organizations decided which parts of their stack were worth owning outright.',
  ],
  [
    'ses_006',
    'A field guide to human approval',
    'talk',
    'trk_society',
    [6],
    30,
    90,
    'Designing the moment a person signs off: what to show, what to log, and when to refuse to proceed.',
  ],
  [
    'ses_007',
    'Small models, serious work',
    'talk',
    'trk_frontier',
    [9],
    30,
    115,
    'The tasks where a tuned small model beats a frontier call on latency, cost, and predictability.',
  ],
  [
    'ses_008',
    'What agents change about operations',
    'panel',
    'trk_operate',
    [0, 12, 14],
    45,
    142,
    'Operators on what actually got faster, what got harder to audit, and which headcount assumptions broke.',
  ],
  [
    'ses_009',
    'Designing an evaluation people trust',
    'workshop',
    'trk_society',
    [15, 13],
    75,
    70,
    'Hands-on: build a rubric your own team will believe, then find the cases where it disagrees with you.',
  ],
  [
    'ses_010',
    'Closing synthesis',
    'keynote',
    'trk_frontier',
    [12],
    35,
    340,
    'The threads that ran through both days, and the open problems worth carrying into next year.',
  ],
  [
    'ses_011',
    'Ask me anything: operating trustworthy AI',
    'panel',
    'trk_operate',
    [12, 14],
    45,
    130,
    'A candid closing conversation about the operational decisions teams still disagree on.',
  ],
] as const

const sessionRecords: Session[] = sessionInputs.map((session) => ({
  id: session[0],
  eventId,
  title: session[1],
  format: session[2],
  summary: session[7],
  trackId: session[3],
  participantIds: session[4].map((index) => participations[index].id),
  durationMinutes: session[5],
  expectedAttendance: session[6],
  status: 'ready',
  updatedAt: seededAt,
  version: 1,
}))

for (const session of sessionRecords) {
  for (const participantId of session.participantIds) {
    participations
      .find((participation) => participation.id === participantId)
      ?.sessionIds.push(session.id)
  }
}

const placementInput = [
  ['ses_001', 'rom_main', '2026-10-04T13:00:00.000Z'],
  ['ses_002', 'rom_studio', '2026-10-04T14:00:00.000Z'],
  ['ses_003', 'rom_main', '2026-10-04T14:00:00.000Z'],
  ['ses_004', 'rom_workshop', '2026-10-04T15:00:00.000Z'],
  ['ses_005', 'rom_studio', '2026-10-04T15:00:00.000Z'],
  ['ses_006', 'rom_main', '2026-10-04T15:00:00.000Z'],
  ['ses_007', 'rom_studio', '2026-10-04T16:15:00.000Z'],
  ['ses_008', 'rom_main', '2026-10-04T16:15:00.000Z'],
  ['ses_009', 'rom_workshop', '2026-10-04T17:00:00.000Z'],
  ['ses_010', 'rom_main', '2026-10-04T18:15:00.000Z'],
] as const

const placements: Placement[] = placementInput.map((placement, index) => {
  const session = sessionRecords.find((record) => record.id === placement[0])!
  const startsAt = placement[2]
  return {
    id: `plc_${String(index + 1).padStart(3, '0')}`,
    eventId,
    sessionId: session.id,
    roomId: placement[1],
    startsAt,
    endsAt: new Date(new Date(startsAt).getTime() + session.durationMinutes * 60_000).toISOString(),
    scheduleVersion: 3,
    published: true,
    version: 1,
  }
})

const initialScheduleRelease: ScheduleRelease = {
  id: 'sch_nyc_2026_v3',
  eventId,
  version: 3,
  publishedAt: seededAt,
  publishedBy: { type: 'system', id: 'system', name: 'ProgramKit' },
  placements: structuredClone(placements),
}

const campaigns: Campaign[] = [
  {
    id: 'cam_001',
    eventId,
    name: 'August confirmation reminder',
    subject: 'Please confirm your participation in AIE NYC',
    body: 'Hi {{first_name}},\n\nPlease confirm your participation and review the next steps in your speaker portal.',
    audience: 'unconfirmed',
    recipientParticipationIds: participations
      .filter((participation) => participation.status === 'invited')
      .map((participation) => participation.id),
    includeEventInvite: true,
    status: 'awaiting_approval',
    createdAt: seededAt,
    approvedAt: null,
    queuedAt: null,
    sentAt: null,
    createdBy: 'Alex Morgan',
    version: 1,
  },
  {
    id: 'cam_002',
    eventId,
    name: 'Welcome confirmed speakers',
    subject: 'Your AIE NYC speaker workspace is ready',
    body: 'Hi {{first_name}},\n\nWe’re delighted to confirm you as a speaker at {{event_name}}. Your speaker workspace is ready for your bio, headshot, and session materials.\n\nThe event is {{event_date}} at {{event_venue}}. We’ve included a calendar invite.\n\nOpen your workspace: {{portal_url}}\n\nThank you,\nThe program team',
    audience: 'custom',
    recipientParticipationIds: participations
      .filter((participation) => participation.status === 'confirmed')
      .slice(0, 6)
      .map((participation) => participation.id),
    includeEventInvite: true,
    status: 'queued',
    createdAt: '2026-07-21T15:00:00.000Z',
    approvedAt: '2026-07-21T15:30:00.000Z',
    queuedAt: '2026-07-21T16:00:00.000Z',
    sentAt: null,
    createdBy: 'Alex Morgan',
    version: 3,
  },
]

const campaignDeliveries: CampaignDelivery[] = campaigns[1].recipientParticipationIds.flatMap(
  (participationId, index) => {
    const participation = participations.find((entry) => entry.id === participationId)
    const person = people.find((entry) => entry.id === participation?.personId)
    if (!participation || !person) return []
    return [
      {
        id: `dlv_welcome_${String(index + 1).padStart(2, '0')}`,
        campaignId: campaigns[1].id,
        eventId,
        participationId,
        personId: person.id,
        recipientName: `${person.firstName} ${person.lastName}`,
        recipientEmail: person.email,
        subject: campaigns[1].subject,
        body: campaigns[1].body
          .replaceAll('{{first_name}}', person.firstName)
          .replaceAll('{{event_name}}', 'AIE NYC 2026')
          .replaceAll('{{event_date}}', 'October 4, 2026')
          .replaceAll('{{event_venue}}', 'Brooklyn Navy Yard, Brooklyn, New York')
          .replaceAll('{{portal_url}}', `/portal/${participationId}`),
        status: 'pending_provider' as const,
        provider: null,
        providerMessageId: null,
        attachmentNames: ['aie-nyc-2026-invite.ics'],
        attemptCount: 0,
        lastError: null,
        createdAt: '2026-07-21T16:00:00.000Z',
        updatedAt: '2026-07-21T16:00:00.000Z',
        version: 1,
      },
    ]
  },
)

const integrations: Integration[] = [
  {
    id: 'int_email',
    name: 'Transactional email',
    kind: 'email',
    status: 'not_configured',
    detail:
      'The durable outbox is ready. Cloudflare Email Service awaits sender-domain verification.',
    lastSeenAt: null,
  },
  {
    id: 'int_webhook',
    name: 'Program website webhook',
    kind: 'webhook',
    status: 'not_configured',
    detail: 'Domain events are recorded; signed webhook delivery is not configured.',
    lastSeenAt: null,
  },
  {
    id: 'int_calendar',
    name: 'Calendar sync',
    kind: 'calendar',
    status: 'connected',
    detail: 'RFC 5545 event invites are available for campaign attachments and direct download.',
    lastSeenAt: seededAt,
  },
  {
    id: 'int_storage',
    name: 'Asset storage',
    kind: 'storage',
    status: 'attention',
    detail:
      'Private R2 upload and download are wired; create the production bucket before release.',
    lastSeenAt: null,
  },
  {
    id: 'int_airtable',
    name: 'Airtable team mirror',
    kind: 'airtable',
    status: 'not_configured',
    detail: 'Optional conflict-aware mirror for submissions, speakers, sessions, and tasks.',
    lastSeenAt: null,
  },
  {
    id: 'int_accelevents',
    name: 'Accelevents program export',
    kind: 'accelevents',
    status: 'not_configured',
    detail:
      'The versioned export outbox is ready; an enterprise API key and target event URL are not connected.',
    lastSeenAt: null,
  },
  {
    id: 'int_api',
    name: 'Public API',
    kind: 'api',
    status: 'connected',
    detail: 'Operation API and MCP endpoint are available.',
    lastSeenAt: '2026-08-07T13:58:00.000Z',
  },
]

export function createSeedState(): WorkspaceState {
  return {
    schemaVersion: 8,
    revision: 1,
    workspace: {
      id: 'wrk_aie',
      name: 'AIE Program Team',
      slug: 'aie',
      timezone: 'America/New_York',
    },
    activeEventId: eventId,
    events: [
      {
        id: eventId,
        name: 'AIE NYC 2026',
        slug: 'aie-nyc-2026',
        venue: 'Brooklyn Navy Yard',
        city: 'Brooklyn, New York',
        startsAt: '2026-10-04T13:00:00.000Z',
        endsAt: '2026-10-05T22:00:00.000Z',
        timezone: 'America/New_York',
        status: 'active',
        publishedScheduleVersion: 3,
        version: 1,
      },
    ],
    people: structuredClone(people),
    participations: structuredClone(participations),
    requirementDefinitions: structuredClone(requirementDefinitions),
    requirementInstances: structuredClone(requirementInstances),
    submissionForms: structuredClone(submissionForms),
    submissionFormFields: structuredClone(submissionFormFields),
    submissions: structuredClone(submissions),
    submissionReceiptDeliveries: structuredClone(submissionReceiptDeliveries),
    assets: structuredClone(assets),
    portalResources: structuredClone(portalResources),
    reviewers: structuredClone(reviewers),
    reviewerTeams: structuredClone(reviewerTeams),
    evaluationPlans: structuredClone(evaluationPlans),
    reviewerAssignments: structuredClone(reviewerAssignments),
    scorecards: structuredClone(scorecards),
    reviewDecisions: structuredClone(reviewDecisions),
    tracks: structuredClone(tracks),
    rooms: structuredClone(rooms),
    sessions: structuredClone(sessionRecords),
    placements: structuredClone(placements),
    scheduleReleases: [structuredClone(initialScheduleRelease)],
    campaigns: structuredClone(campaigns),
    campaignDeliveries: structuredClone(campaignDeliveries),
    changeSets: [
      {
        id: 'chg_agent_001',
        eventId,
        title: 'Give Small models, serious work more room',
        description:
          'Move the session to Main stage at 1:00 PM local time to fit the current audience estimate.',
        origin: 'agent',
        operations: [
          {
            operation: 'schedule.move-session',
            input: {
              placementId: 'plc_007',
              roomId: 'rom_main',
              startsAt: '2026-10-04T17:00:00.000Z',
            },
            expectedVersions: { plc_007: 1 },
          },
        ],
        status: 'awaiting_approval',
        impactSummary: [
          'Moves one 30-minute session from Studio to Main stage.',
          'Increases available capacity from 150 to 420.',
          'Leaves all participant and room constraints valid.',
        ],
        warnings: ['The public agenda will not change until the schedule is published.'],
        createdBy: 'ProgramKit Agent',
        approvedBy: null,
        createdAt: '2026-08-07T15:10:00.000Z',
        updatedAt: '2026-08-07T15:10:00.000Z',
        committedEventIds: [],
        version: 1,
      },
    ],
    integrations: structuredClone(integrations),
    acceleventsExports: [],
    domainEvents: [
      {
        id: 'dev_001',
        sequence: 1,
        type: 'workspace.seeded',
        occurredAt: seededAt,
        actor: { type: 'system', id: 'system', name: 'ProgramKit' },
        aggregate: { type: 'workspace', id: 'wrk_aie', version: 1 },
        operation: 'workspace.seed',
        summary: 'Created the AIE NYC demonstration workspace.',
        data: { people: people.length, sessions: sessionRecords.length },
      },
      {
        id: 'dev_002',
        sequence: 2,
        type: 'import.completed',
        occurredAt: '2026-08-07T14:05:00.000Z',
        actor: { type: 'staff', id: 'usr_alex', name: 'Alex Morgan' },
        aggregate: { type: 'event', id: eventId, version: 1 },
        operation: 'import.commit',
        summary: 'Imported 16 participants and 10 sessions from the program workbook.',
        data: { created: 26, duplicates: 2, skipped: 0 },
      },
      {
        id: 'dev_003',
        sequence: 3,
        type: 'change-set.created',
        occurredAt: '2026-08-07T15:10:00.000Z',
        actor: { type: 'agent', id: 'agent_programkit', name: 'ProgramKit Agent' },
        aggregate: { type: 'change-set', id: 'chg_agent_001', version: 1 },
        operation: 'change-set.create',
        summary: 'Proposed moving Small models, serious work to Main stage.',
        data: { proposedOperation: 'schedule.move-session' },
      },
    ],
    recentCommandResults: [],
  }
}
