/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperatorRouteImport } from './routes/_operator'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as OperatorIndexRouteImport } from './routes/_operator.index'
import { Route as OperatorAgentRouteImport } from './routes/_operator.agent'
import { Route as OperatorChangesRouteImport } from './routes/_operator.changes'
import { Route as OperatorCommunicationsRouteImport } from './routes/_operator.communications'
import { Route as OperatorCrmRouteImport } from './routes/_operator.crm'
import { Route as OperatorFilesRouteImport } from './routes/_operator.files'
import { Route as OperatorFormsRouteImport } from './routes/_operator.forms'
import { Route as OperatorIntegrationsRouteImport } from './routes/_operator.integrations'
import { Route as OperatorPeopleRouteImport } from './routes/_operator.people'
import { Route as OperatorReadinessRouteImport } from './routes/_operator.readiness'
import { Route as OperatorReviewsRouteImport } from './routes/_operator.reviews'
import { Route as OperatorScheduleRouteImport } from './routes/_operator.schedule'
import { Route as OperatorSessionsRouteImport } from './routes/_operator.sessions'
import { Route as OperatorSettingsRouteImport } from './routes/_operator.settings'
import { Route as OperatorSubmissionsRouteImport } from './routes/_operator.submissions'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as PortalParticipationIdRouteImport } from './routes/portal.$participationId'
import { Route as ReviewerReviewerIdRouteImport } from './routes/reviewer.$reviewerId'
import { Route as SubmitFormSlugRouteImport } from './routes/submit.$formSlug'
import { Route as PortalParticipationIdPortalAccessKeyRouteImport } from './routes/portal.$participationId_.$portalAccessKey'
import { Route as ReviewerReviewerIdReviewerAccessKeyRouteImport } from './routes/reviewer.$reviewerId_.$reviewerAccessKey'
import { Route as SubmitFormSlugMineSpeakerAccessKeyRouteImport } from './routes/submit.$formSlug_.mine.$speakerAccessKey'

const OperatorRoute = OperatorRouteImport.update({
  id: '/_operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAgentRoute = OperatorAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorChangesRoute = OperatorChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorCommunicationsRoute = OperatorCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorCrmRoute = OperatorCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorFilesRoute = OperatorFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorFormsRoute = OperatorFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorIntegrationsRoute = OperatorIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPeopleRoute = OperatorPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorReadinessRoute = OperatorReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorReviewsRoute = OperatorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorScheduleRoute = OperatorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorSessionsRoute = OperatorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorSettingsRoute = OperatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorSubmissionsRoute = OperatorSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => OperatorRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const PortalParticipationIdRoute = PortalParticipationIdRouteImport.update({
  id: '/portal/$participationId',
  path: '/portal/$participationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerReviewerIdRoute = ReviewerReviewerIdRouteImport.update({
  id: '/reviewer/$reviewerId',
  path: '/reviewer/$reviewerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitFormSlugRoute = SubmitFormSlugRouteImport.update({
  id: '/submit/$formSlug',
  path: '/submit/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalParticipationIdPortalAccessKeyRoute =
  PortalParticipationIdPortalAccessKeyRouteImport.update({
    id: '/portal/$participationId_/$portalAccessKey',
    path: '/portal/$participationId/$portalAccessKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReviewerReviewerIdReviewerAccessKeyRoute =
  ReviewerReviewerIdReviewerAccessKeyRouteImport.update({
    id: '/reviewer/$reviewerId_/$reviewerAccessKey',
    path: '/reviewer/$reviewerId/$reviewerAccessKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubmitFormSlugMineSpeakerAccessKeyRoute =
  SubmitFormSlugMineSpeakerAccessKeyRouteImport.update({
    id: '/submit/$formSlug_/mine/$speakerAccessKey',
    path: '/submit/$formSlug/mine/$speakerAccessKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof OperatorIndexRoute
  '/access': typeof AccessRoute
  '/agenda': typeof AgendaRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agent': typeof OperatorAgentRoute
  '/changes': typeof OperatorChangesRoute
  '/communications': typeof OperatorCommunicationsRoute
  '/crm': typeof OperatorCrmRoute
  '/files': typeof OperatorFilesRoute
  '/forms': typeof OperatorFormsRoute
  '/integrations': typeof OperatorIntegrationsRoute
  '/people': typeof OperatorPeopleRoute
  '/readiness': typeof OperatorReadinessRoute
  '/reviews': typeof OperatorReviewsRoute
  '/schedule': typeof OperatorScheduleRoute
  '/sessions': typeof OperatorSessionsRoute
  '/settings': typeof OperatorSettingsRoute
  '/submissions': typeof OperatorSubmissionsRoute
  '/docs/$': typeof DocsSplatRoute
  '/portal/$participationId': typeof PortalParticipationIdRoute
  '/reviewer/$reviewerId': typeof ReviewerReviewerIdRoute
  '/submit/$formSlug': typeof SubmitFormSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/portal/$participationId/$portalAccessKey': typeof PortalParticipationIdPortalAccessKeyRoute
  '/reviewer/$reviewerId/$reviewerAccessKey': typeof ReviewerReviewerIdReviewerAccessKeyRoute
  '/submit/$formSlug/mine/$speakerAccessKey': typeof SubmitFormSlugMineSpeakerAccessKeyRoute
}
export interface FileRoutesByTo {
  '/access': typeof AccessRoute
  '/agenda': typeof AgendaRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agent': typeof OperatorAgentRoute
  '/changes': typeof OperatorChangesRoute
  '/communications': typeof OperatorCommunicationsRoute
  '/crm': typeof OperatorCrmRoute
  '/files': typeof OperatorFilesRoute
  '/forms': typeof OperatorFormsRoute
  '/integrations': typeof OperatorIntegrationsRoute
  '/people': typeof OperatorPeopleRoute
  '/readiness': typeof OperatorReadinessRoute
  '/reviews': typeof OperatorReviewsRoute
  '/schedule': typeof OperatorScheduleRoute
  '/sessions': typeof OperatorSessionsRoute
  '/settings': typeof OperatorSettingsRoute
  '/submissions': typeof OperatorSubmissionsRoute
  '/docs/$': typeof DocsSplatRoute
  '/portal/$participationId': typeof PortalParticipationIdRoute
  '/reviewer/$reviewerId': typeof ReviewerReviewerIdRoute
  '/submit/$formSlug': typeof SubmitFormSlugRoute
  '/': typeof OperatorIndexRoute
  '/docs': typeof DocsIndexRoute
  '/portal/$participationId/$portalAccessKey': typeof PortalParticipationIdPortalAccessKeyRoute
  '/reviewer/$reviewerId/$reviewerAccessKey': typeof ReviewerReviewerIdReviewerAccessKeyRoute
  '/submit/$formSlug/mine/$speakerAccessKey': typeof SubmitFormSlugMineSpeakerAccessKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_operator': typeof OperatorRouteWithChildren
  '/access': typeof AccessRoute
  '/agenda': typeof AgendaRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_operator/agent': typeof OperatorAgentRoute
  '/_operator/changes': typeof OperatorChangesRoute
  '/_operator/communications': typeof OperatorCommunicationsRoute
  '/_operator/crm': typeof OperatorCrmRoute
  '/_operator/files': typeof OperatorFilesRoute
  '/_operator/forms': typeof OperatorFormsRoute
  '/_operator/integrations': typeof OperatorIntegrationsRoute
  '/_operator/people': typeof OperatorPeopleRoute
  '/_operator/readiness': typeof OperatorReadinessRoute
  '/_operator/reviews': typeof OperatorReviewsRoute
  '/_operator/schedule': typeof OperatorScheduleRoute
  '/_operator/sessions': typeof OperatorSessionsRoute
  '/_operator/settings': typeof OperatorSettingsRoute
  '/_operator/submissions': typeof OperatorSubmissionsRoute
  '/docs/$': typeof DocsSplatRoute
  '/portal/$participationId': typeof PortalParticipationIdRoute
  '/reviewer/$reviewerId': typeof ReviewerReviewerIdRoute
  '/submit/$formSlug': typeof SubmitFormSlugRoute
  '/_operator/': typeof OperatorIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/portal/$participationId_/$portalAccessKey': typeof PortalParticipationIdPortalAccessKeyRoute
  '/reviewer/$reviewerId_/$reviewerAccessKey': typeof ReviewerReviewerIdReviewerAccessKeyRoute
  '/submit/$formSlug_/mine/$speakerAccessKey': typeof SubmitFormSlugMineSpeakerAccessKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/agenda'
    | '/demo'
    | '/docs'
    | '/privacy'
    | '/terms'
    | '/agent'
    | '/changes'
    | '/communications'
    | '/crm'
    | '/files'
    | '/forms'
    | '/integrations'
    | '/people'
    | '/readiness'
    | '/reviews'
    | '/schedule'
    | '/sessions'
    | '/settings'
    | '/submissions'
    | '/docs/$'
    | '/portal/$participationId'
    | '/reviewer/$reviewerId'
    | '/submit/$formSlug'
    | '/docs/'
    | '/portal/$participationId/$portalAccessKey'
    | '/reviewer/$reviewerId/$reviewerAccessKey'
    | '/submit/$formSlug/mine/$speakerAccessKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access'
    | '/agenda'
    | '/demo'
    | '/privacy'
    | '/terms'
    | '/agent'
    | '/changes'
    | '/communications'
    | '/crm'
    | '/files'
    | '/forms'
    | '/integrations'
    | '/people'
    | '/readiness'
    | '/reviews'
    | '/schedule'
    | '/sessions'
    | '/settings'
    | '/submissions'
    | '/docs/$'
    | '/portal/$participationId'
    | '/reviewer/$reviewerId'
    | '/submit/$formSlug'
    | '/'
    | '/docs'
    | '/portal/$participationId/$portalAccessKey'
    | '/reviewer/$reviewerId/$reviewerAccessKey'
    | '/submit/$formSlug/mine/$speakerAccessKey'
  id:
    | '__root__'
    | '/_operator'
    | '/access'
    | '/agenda'
    | '/demo'
    | '/docs'
    | '/privacy'
    | '/terms'
    | '/_operator/agent'
    | '/_operator/changes'
    | '/_operator/communications'
    | '/_operator/crm'
    | '/_operator/files'
    | '/_operator/forms'
    | '/_operator/integrations'
    | '/_operator/people'
    | '/_operator/readiness'
    | '/_operator/reviews'
    | '/_operator/schedule'
    | '/_operator/sessions'
    | '/_operator/settings'
    | '/_operator/submissions'
    | '/docs/$'
    | '/portal/$participationId'
    | '/reviewer/$reviewerId'
    | '/submit/$formSlug'
    | '/_operator/'
    | '/docs/'
    | '/portal/$participationId_/$portalAccessKey'
    | '/reviewer/$reviewerId_/$reviewerAccessKey'
    | '/submit/$formSlug_/mine/$speakerAccessKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OperatorRoute: typeof OperatorRouteWithChildren
  AccessRoute: typeof AccessRoute
  AgendaRoute: typeof AgendaRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PortalParticipationIdRoute: typeof PortalParticipationIdRoute
  ReviewerReviewerIdRoute: typeof ReviewerReviewerIdRoute
  SubmitFormSlugRoute: typeof SubmitFormSlugRoute
  PortalParticipationIdPortalAccessKeyRoute: typeof PortalParticipationIdPortalAccessKeyRoute
  ReviewerReviewerIdReviewerAccessKeyRoute: typeof ReviewerReviewerIdReviewerAccessKeyRoute
  SubmitFormSlugMineSpeakerAccessKeyRoute: typeof SubmitFormSlugMineSpeakerAccessKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_operator': {
      id: '/_operator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/': {
      id: '/_operator/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/agent': {
      id: '/_operator/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof OperatorAgentRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/changes': {
      id: '/_operator/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof OperatorChangesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/communications': {
      id: '/_operator/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof OperatorCommunicationsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/crm': {
      id: '/_operator/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof OperatorCrmRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/files': {
      id: '/_operator/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof OperatorFilesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/forms': {
      id: '/_operator/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof OperatorFormsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/integrations': {
      id: '/_operator/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof OperatorIntegrationsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/people': {
      id: '/_operator/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof OperatorPeopleRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/readiness': {
      id: '/_operator/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof OperatorReadinessRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/reviews': {
      id: '/_operator/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof OperatorReviewsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/schedule': {
      id: '/_operator/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof OperatorScheduleRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/sessions': {
      id: '/_operator/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof OperatorSessionsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/settings': {
      id: '/_operator/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OperatorSettingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/submissions': {
      id: '/_operator/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof OperatorSubmissionsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/portal/$participationId': {
      id: '/portal/$participationId'
      path: '/portal/$participationId'
      fullPath: '/portal/$participationId'
      preLoaderRoute: typeof PortalParticipationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/$reviewerId': {
      id: '/reviewer/$reviewerId'
      path: '/reviewer/$reviewerId'
      fullPath: '/reviewer/$reviewerId'
      preLoaderRoute: typeof ReviewerReviewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$formSlug': {
      id: '/submit/$formSlug'
      path: '/submit/$formSlug'
      fullPath: '/submit/$formSlug'
      preLoaderRoute: typeof SubmitFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$participationId_/$portalAccessKey': {
      id: '/portal/$participationId_/$portalAccessKey'
      path: '/portal/$participationId/$portalAccessKey'
      fullPath: '/portal/$participationId/$portalAccessKey'
      preLoaderRoute: typeof PortalParticipationIdPortalAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/$reviewerId_/$reviewerAccessKey': {
      id: '/reviewer/$reviewerId_/$reviewerAccessKey'
      path: '/reviewer/$reviewerId/$reviewerAccessKey'
      fullPath: '/reviewer/$reviewerId/$reviewerAccessKey'
      preLoaderRoute: typeof ReviewerReviewerIdReviewerAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$formSlug_/mine/$speakerAccessKey': {
      id: '/submit/$formSlug_/mine/$speakerAccessKey'
      path: '/submit/$formSlug/mine/$speakerAccessKey'
      fullPath: '/submit/$formSlug/mine/$speakerAccessKey'
      preLoaderRoute: typeof SubmitFormSlugMineSpeakerAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OperatorRouteChildren {
  OperatorAgentRoute: typeof OperatorAgentRoute
  OperatorChangesRoute: typeof OperatorChangesRoute
  OperatorCommunicationsRoute: typeof OperatorCommunicationsRoute
  OperatorCrmRoute: typeof OperatorCrmRoute
  OperatorFilesRoute: typeof OperatorFilesRoute
  OperatorFormsRoute: typeof OperatorFormsRoute
  OperatorIntegrationsRoute: typeof OperatorIntegrationsRoute
  OperatorPeopleRoute: typeof OperatorPeopleRoute
  OperatorReadinessRoute: typeof OperatorReadinessRoute
  OperatorReviewsRoute: typeof OperatorReviewsRoute
  OperatorScheduleRoute: typeof OperatorScheduleRoute
  OperatorSessionsRoute: typeof OperatorSessionsRoute
  OperatorSettingsRoute: typeof OperatorSettingsRoute
  OperatorSubmissionsRoute: typeof OperatorSubmissionsRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAgentRoute: OperatorAgentRoute,
  OperatorChangesRoute: OperatorChangesRoute,
  OperatorCommunicationsRoute: OperatorCommunicationsRoute,
  OperatorCrmRoute: OperatorCrmRoute,
  OperatorFilesRoute: OperatorFilesRoute,
  OperatorFormsRoute: OperatorFormsRoute,
  OperatorIntegrationsRoute: OperatorIntegrationsRoute,
  OperatorPeopleRoute: OperatorPeopleRoute,
  OperatorReadinessRoute: OperatorReadinessRoute,
  OperatorReviewsRoute: OperatorReviewsRoute,
  OperatorScheduleRoute: OperatorScheduleRoute,
  OperatorSessionsRoute: OperatorSessionsRoute,
  OperatorSettingsRoute: OperatorSettingsRoute,
  OperatorSubmissionsRoute: OperatorSubmissionsRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OperatorRoute: OperatorRouteWithChildren,
  AccessRoute: AccessRoute,
  AgendaRoute: AgendaRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PortalParticipationIdRoute: PortalParticipationIdRoute,
  ReviewerReviewerIdRoute: ReviewerReviewerIdRoute,
  SubmitFormSlugRoute: SubmitFormSlugRoute,
  PortalParticipationIdPortalAccessKeyRoute:
    PortalParticipationIdPortalAccessKeyRoute,
  ReviewerReviewerIdReviewerAccessKeyRoute:
    ReviewerReviewerIdReviewerAccessKeyRoute,
  SubmitFormSlugMineSpeakerAccessKeyRoute:
    SubmitFormSlugMineSpeakerAccessKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
